### ISSUE TITLE
Called a function but it displaying array itself without echo

### ISSUE THREAD

**Issue by iSarahSajjad** [roanuz/php-cricket#2]
I used a function $getNewsAgg = $phpCricket->getNewsAggregation(); 
but it start displaying on my web pages without echo. i want to store in a global function the will use it 
but it is displaying on my all pages itself

**Comment by SaiSudheerRz** [comment]
> I used a function $getNewsAgg = $phpCricket->getNewsAggregation();
> but it start displaying on my web pages without echo. i want to store in a global function the will use it
> but it is displaying on my all pages itself

We fixed this issue and updated the source code.
